In [1]:
# Numpy
import numpy as np
import time



In [9]:
list=[i for i in range(12000)]
start_time = process_time()
list=[i+5 for i in list]
end_time = process_time()
print(end_time-start_time)

NameError: name 'process_time' is not defined

In [10]:
list=[1,23,3,4,56,6]
print(list)
type(list)

[1, 23, 3, 4, 56, 6]


list

In [11]:
np_array=np.array([12,3,4,4,5,8])
type(np_array)

numpy.ndarray

In [15]:
var=np.array([(1,2,3,4,5),(2,3,4,5,5),(2,3,4,5,6)])
var.shape

(3, 5)

In [20]:
ar=np.ones((4,5))
print(ar)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
x=np.random.random((4,4))
print(x)

[[0.20093709 0.74809576 0.33893973 0.23459458]
 [0.94955507 0.61554926 0.86512418 0.5379447 ]
 [0.12770748 0.56072401 0.40809582 0.97973075]
 [0.08433126 0.29917608 0.37478324 0.76448948]]


In [25]:
q=np.arange(12,20,9)
print(q)

[12]


In [26]:
list=[1,2,3,4,5,6,7,8]
np_array=np.asarray(list)
print(np_array)
type(np_array)

[1 2 3 4 5 6 7 8]


numpy.ndarray

In [28]:
tuple=[1,2,3,4,5,6,7,8]
np_array=np.asarray(tuple)
print(np_array)
type(np_array)

[1 2 3 4 5 6 7 8]


numpy.ndarray

In [31]:
x=np.random.randint(10,100,(4,4))
print(x)

[[33 33 91 59]
 [41 26 14 13]
 [55 14 95 19]
 [31 68 95 32]]


In [32]:
print(x.ndim)

2


In [33]:
print(x.dtype)

int32


In [41]:
a=np.random.randint(10,100,(3,3))
b=np.random.randint(10,100,(3,3))
print(np.add(a,b))
print(a)
print(b)
print(a+b)
print(a/b)

[[ 37  82 152]
 [131  92  36]
 [ 61 111 136]]
[[16 31 53]
 [64 74 18]
 [21 32 83]]
[[21 51 99]
 [67 18 18]
 [40 79 53]]
[[ 37  82 152]
 [131  92  36]
 [ 61 111 136]]
[[0.76190476 0.60784314 0.53535354]
 [0.95522388 4.11111111 1.        ]
 [0.525      0.40506329 1.56603774]]


In [50]:
a=np.random.randint(1,10,(3,2))
print(a)


[[7 5]
 [5 7]
 [2 5]]


In [52]:
trans=np.transpose(a)
print(trans)
print(a.shape)

[[7 5 2]
 [5 7 5]]
(3, 2)
